services:
  envmesh-api:
    container_name: envmesh-api
    build: ./
    ports:
      - 8080:8080
    environment:
      - TZ: Europe/Zurich
      - APP_ENV: development
      - APP_PORT: 8080
    networks:
     - envmesh-net
    restart: on-failure