services:
  envmesh-api:
    container_name: database
    image: postgres:18-alpine
    ports:
    - 5432:5432
    environment:
      TZ: Europe/Zurich
      APP_ENV: development
      APP_PORT: 8080
      # TODO: implement a solution to randomise these values; database-api is the only container that should access the database
      POSTGRES_USER: envmesh
      POSTGRES_PASSWORD: envmesh
      POSTGRES_DB: envmesh
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
     - envmesh-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U envmesh"]
      interval: 5s
      timeout: 3s
      retries: 5

    restart: on-failure